parameters:
    tmas.cron.time_provider.class: DateRepetition\TimeProvider
    tmas.cron.scheduler.class: Tmas\CronBundle\Service\CronScheduler

services:
    tmas.cron.time_provider:
        class: %tmas.cron.time_provider.class%

    tmas.cron.scheduler:
        class: %tmas.cron.scheduler.class%
        arguments: [@tmas.cron.time_provider]
